spring:
    application:
        name: online-store-product
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/products}
        username: ${SPRING_DATASOURCE_USERNAME:postgres}
        password: ${SPRING_DATASOURCE_PASSWORD:password}
    
server:
    port: ${SERVER_PORT:8080}
    
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}

app:
    security:
        api-key: kxMcvCpeRe7Nv6WSrFDmvA37FWG04sz3cyRMA0y8
