[versions]
springbootVersion = "4.0.2"
springDependencyManagementVersion = "1.1.7"
lombokPluginVersion = "9.2.0"
springframeworkVersion = "7.0.4"
springDataBomVersion = "2025.1.3"
junitVersion = "6.0.2"
jakartaValidationVersion = "3.1.1"
jakartaAnnotationVersion = "2.1.0"
jakartaPersistenceVersion = "3.2.0"
lombokVersion = "1.18.42"

[libraries]
jakartaValidationApi = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakartaValidationVersion" }
jakartaAnnotationApi = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakartaAnnotationVersion" }
jakartaPersistenceApi = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakartaPersistenceVersion" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombokVersion" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springbootVersion" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVersion" }
lombok = { id = "io.freefair.lombok", version.ref = "lombokPluginVersion" }