services:
  pg_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - ./pg_init.sql:/docker-entrypoint-initdb.d/init.sql

  eureka-server:
    build:
      context: ..
      dockerfile: eureka-server/Dockerfile
    container_name: eureka-server
    hostname: eureka-server
    ports:
      - "8761:8761"

  product-app:
    build:
      context: ..
      dockerfile: product/Dockerfile
    container_name: product-app
    hostname: product-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg_db:5432/products
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: product-app
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
      EUREKA_INSTANCE_NON_SECURE_PORT: "8080"
    depends_on:
      - pg_db
      - eureka-server
    restart: on-failure
    ports:
      - "8080:8080"
  
  mongo_db:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

  inventory-app:
    build:
      context: ..
      dockerfile: inventory/Dockerfile
    container_name: inventory-app
    hostname: inventory-app
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://admin:password@mongo_db:27017/inventory?authSource=admin
      SPRING_DATA_MONGODB_DATABASE: inventory
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: inventory-app
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: "false"
      EUREKA_INSTANCE_NON_SECURE_PORT: "8081"
    depends_on:
      - eureka-server
      - mongo_db
    restart: on-failure
    ports:
      - "8081:8081"
  
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"   
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
