[versions]
springbootVersion = "4.0.2"
springDependencyManagementVersion = "1.1.7"
lombokPluginVersion = "9.2.0"
springCloudVersion = "2025.1.1"

[libraries]
springCloudDependencies = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "springCloudVersion" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springbootVersion" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVersion" }
lombok = { id = "io.freefair.lombok", version.ref = "lombokPluginVersion" }