[versions]
springbootVersion = "4.0.2"
springDependencyManagementVersion = "1.1.7"
lombokPluginVersion = "9.2.0"
mapstructVersion = "1.6.3"
springDocVersion = "2.8.5"
swaggerAnnotationsVersion = "2.2.41"
springframeworkVersion = "7.0.4"
springDataBomVersion = "2025.1.3"
jakartaValidationVersion = "3.1.1"
junitVersion = "6.0.2"
jakartaAnnotationVersion = "2.1.0"
jakartaPersistenceVersion = "3.2.0"
lombokVersion = "1.18.42"
jacksonVersion = "2.14.1"

[libraries]
mapstruct = { module = "org.mapstruct:mapstruct", version.ref = "mapstructVersion" }
mapstructProcessor = { module = "org.mapstruct:mapstruct-processor", version.ref = "mapstructVersion" }
springDocOpenApi = { module = "org.springdoc:springdoc-openapi-starter-webmvc-ui", version.ref = "springDocVersion" }
swaggerAnnotations = { module = "io.swagger.core.v3:swagger-annotations", version.ref = "swaggerAnnotationsVersion" }
jakartaValidationApi = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakartaValidationVersion" }
jakartaAnnotationApi = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakartaAnnotationVersion" }
jakartaPersistenceApi = { module = "jakarta.persistence:jakarta.persistence-api", version.ref = "jakartaPersistenceVersion" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombokVersion" }
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonVersion" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springbootVersion" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVersion" }
lombok = { id = "io.freefair.lombok", version.ref = "lombokPluginVersion" }